name: Beta

on:
  pull_request:
  push:
    branches:
      - master
      - 'renovate/*'
    paths:
      - 'packages/beta/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn workspace beta test:ci
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy theme
        uses: minimaluminium/action-deploy-theme@custom-dir
        with:
          api-url: ${{ secrets.BETA_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.BETA_GHOST_ADMIN_API_KEY }}
          theme-dir: packages/beta
