name: Bulletin

on:
  pull_request:
  push:
    branches:
      - master
      - 'renovate/*'
    paths:
      - 'packages/bulletin/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test:ci --theme bulletin
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy theme
        uses: minimaluminium/action-deploy-theme@custom-dir
        with:
          api-url: ${{ secrets.BULLETIN_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.BULLETIN_GHOST_ADMIN_API_KEY }}
          theme-dir: packages/bulletin
